# Generated by Django 4.2.1 on 2023-06-01 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0014_use_autofields_for_pk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proyecto', '0002_alter_proyecto_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='schedule.event')),
                ('titulo', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=20)),
                ('inicio', models.DateField()),
                ('final', models.DateField()),
                ('description_event', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('schedule.event',),
        ),
    ]
