# Generated by Django 4.2.1 on 2023-06-02 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0006_alter_proyecto_participantes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='Participantes',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
