# Generated by Django 4.2.1 on 2023-06-02 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0007_alter_proyecto_participantes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='Participantes',
        ),
    ]
