# Generated by Django 4.2.1 on 2023-06-02 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0009_proyecto_participantes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='Participantes',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='descripcion',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
